### PR TITLE
update https and ftp links

### PR DESCRIPTION
**Pull request by sysdev-isu**

### CODE REVIEW

**Comment by sysdev-isu** [comment]
# ./almalinuxos_mirror_sync 
receiving file list ... done

sent 41 bytes  received 9,253,265 bytes  1,233,774.13 bytes/sec
total size is 594,911,555,736  speedup is 64,291.78

**Comment by jonathanspw** [comment]
The https mirror is completely unavailable.

https://downforeveryoneorjustme.com/mirrors.isu.net.sa?proto=https

**Comment by sysdev-isu** [comment]
It is fixed now.

**Comment by jonathanspw** [comment]
Looks like you need to install the CA for your cert.

https://www.sslshopper.com/ssl-checker.html#hostname=mirrors.isu.net.sa

**Comment by sysdev-isu** [comment]
CA has been installed

**Pull request merged**
