### PR TITLE
Create almalinux.jetserver.co.il.yml

### PR DESCRIPTION
**Pull request by JetServerCloud**
AlmaLinux mirror from Jetserver Cloud

### CODE REVIEW

**Comment by codyro** [comment]
Hello, 

Thank you for the mirror! It looks like it's not syncing properly. Would you mind investigating before we merge this in? 

Thanks! 

> Sun Mar 24 07:38:08 UTC 2024

**Comment by codyro** [comment]
We'll be moving the vaults off the main repos soon, which should free up a lot of space.

It looks like this is still reporting as out-of-date: `Sun Mar 24 07:38:08 UTC 2024`

If you're curious, I'm pulling this from https://almalinux.jetserver.co.il/timestamp.txt, which the mirror service uses to help determine if a mirror is up-to-date and should be listed. As-is, your mirror wouldn't show up even if it were merged.

**Comment by JetServerCloud** [comment]
> We'll be moving the vaults off the main repos soon, which should free up a lot of space.
> 
> It looks like this is still reporting as out-of-date: `Sun Mar 24 07:38:08 UTC 2024`
> 
> If you're curious, I'm pulling this from https://almalinux.jetserver.co.il/timestamp.txt, which the mirror service uses to help determine if a mirror is up-to-date and should be listed. As-is, your mirror wouldn't show up even if it were merged.

Unfortunately I'm getting an error that I don't understand the reason behind it. 
The initial sync was a success, we've managed to get the full 973G of data. but the cron we've set isn't working for some reason.

This is the cron:

```
0 */3 * * * sleep $(((RANDOM\%3500)+1)) && /usr/bin/flock -n /var/run/almalinux_rsync.lock -c "/usr/bin/rsync -avSH --exclude='.~tmp~' --delete-delay --delay-updates rsync://[rsync.repo.almalinux.org/almalinux/](http://rsync.repo.almalinux.org/almalinux/) /Files-Path/"
```

When I try to run the command manually, this is what I get:

```
-bash: (RANDOM\%3500)+1: syntax error: invalid arithmetic operator (error token is "\%3500)+1")
```

And when I try to run it this way:

```
/usr/bin/flock -n /var/run/almalinux_rsync.lock -c "/usr/bin/rsync -avSH --exclude='.~tmp~' --delete-delay --delay-updates rsync://[rsync.repo.almalinux.org/almalinux/](http://rsync.repo.almalinux.org/almalinux/) /Files-Path/"
```

This is what I get:
```
rsync: [Receiver] failed to connect to [rsync.repo.almalinux.org](http://rsync.repo.almalinux.org/) (162.43.206.5): Connection refused (111)
rsync: [Receiver] failed to connect to [rsync.repo.almalinux.org](http://rsync.repo.almalinux.org/) (2605:21c0:1000:4e::5): Network is unreachable (101)
rsync error: error in socket IO (code 10) at clientserver.c(139) [Receiver=3.2.7]
```

I appreciate the help!

**Comment by jonathanspw** [comment]
It looks like the URL(s) you copied have markdown in them.  How exactly did you copy them?

**Comment by JetServerCloud** [comment]
Hello,

We found a firewall problem, but it's fixed now. Please check.

**Comment by codyro** [comment]
It looks like the `https` URL is throwing a `403`:

```shell
root@c ~# curl -I https://almalinux.jetserver.co.il
HTTP/1.1 403 Forbidden
Server: nginx/1.14.1
Date: Mon, 15 Apr 2024 10:42:59 GMT
Content-Type: text/html
Content-Length: 169
Connection: keep-alive
```

**Comment by JetServerCloud** [comment]
> It looks like the `https` URL is throwing a `403`:
> 
> ```shell
> root@c ~# curl -I https://almalinux.jetserver.co.il
> HTTP/1.1 403 Forbidden
> Server: nginx/1.14.1
> Date: Mon, 15 Apr 2024 10:42:59 GMT
> Content-Type: text/html
> Content-Length: 169
> Connection: keep-alive
> ```

Hello,

Directory listing was off over https. I've enabled it and it looks like it's working just fine now.

**Review by codyro — APPROVED** [review]

**Comment by codyro** [comment]
Looks good! Thanks for the mirror @JetServerCloud & @Noam-Alum

**Pull request merged**
