### PR TITLE
Create almalinux.mirrors.behostings.net.yml

### PR DESCRIPTION
**Pull request by basilm1989**
---
name: almalinux.mirrors.behostings.net
address:
  http: http://almalinux.mirrors.behostings.net
  https: https://almalinux.mirrors.behostings.net
geolocation:
  country: BE
  state_province: Liege
  city:  Aywaille
update_frequency: 3h
sponsor: Behostings
sponsor_url: https://www.behostings.com
email: basil.m@thgnet.net
...

### CODE REVIEW

**Comment by jonathanspw** [comment]
Please use an email address that does not point to a generic helpdesk/autoresponder.

**Comment by basilm1989** [comment]
> Please use an email address that does not point to a generic helpdesk/autoresponder.

Okay, thank you.

**Comment by basilm1989** [comment]
> Please use an email address that does not point to a generic helpdesk/autoresponder.

Why during the pull request it shows failed >>  "All checks have failed" 

Yesterday, it failed due to geolocation data, I have corrected it and updated, but still shows error while pull request. What should I correct ?

**Comment by soksanichenko** [comment]
@basilm1989 Hi.
Your mirror's config doesn't have necessary field `update_frequency`. Please add it to the config.
Thank you!

**Comment by basilm1989** [comment]
> @basilm1989 Hi. Your mirror's config doesn't have necessary field `update_frequency`. Please add it to the config. Thank you!

Could you have a check now.

**Pull request closed without merging**
