### PR TITLE
Create mirrors.ucr.ac.cr.yml

### PR DESCRIPTION
**Pull request by valarauco**
Adding public mirror hosted at Universidad de Costa Rica

### CODE REVIEW

**Comment by jonathanspw** [comment]
"Central America" is not a valid continent.  Can you please remove that line entirely (the system will pull it automatically based on the country) or change it to "South America"?

**Comment by valarauco** [comment]
Central America should be valid. Sometimes they put us in North America and other times in the South. We are small but we exist. 🤣
According to Wikipedia we are part of North America, tho 😅

**Comment by jonathanspw** [comment]
OpenStreetMap/Nominatim says South America https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=120027&class=boundary

Either way all will be fine with the line removed.  GeoIP will pull it appropriately.

**Comment by jonathanspw** [comment]
Whoops, we're talking about Costa Rica not Columbia :)  So North for sure.

**Comment by valarauco** [comment]
Hohoho
Relax, sometimes people also confuse us with Puerto Rico 👍

**Pull request merged**
