### PR TITLE
Create mirror.aarnet.edu.au.yml

### PR DESCRIPTION
**Pull request by tim82au**
Add mirror.aarnet.edu.au.yml (AARNet Ticket: SD-47729)

### CODE REVIEW

**Comment by jonathanspw** [comment]
Thank you!

**Comment by jonathanspw** [comment]
Please add the geolocation section to the mirror config.

**Comment by tim82au** [comment]
Sorry about that! 

Our mirror exists in several states, is continent and country sufficient for geolocation?

**Comment by jonathanspw** [comment]
> Sorry about that!
> 
> Our mirror exists in several states, is continent and country sufficient for geolocation?

So it's multiple mirrors?  If so it'd be ideal to have an entry per individual mirror, even if the URLs are identical because we route traffic using geolocation.  Assuming you're using anycast or similar having multiple in our mirror list would compliment that, not interfere with it.

**Comment by tim82au** [comment]
The others are used in failover scenarios. I've added the geolocation details for the primary.

**Pull request merged**
