### PR TITLE
Create mirror.herza.id

### PR DESCRIPTION
**Pull request by herzadigital**

### CODE REVIEW

**Comment by andrewlukoshko** [comment]
Hello and thanks for mirror!
Actually I see the following issues:

1. Mirror looks outdated. Did you setup cron?
2. Mirror file should be placed in mirrors.d/ folder like other mirrors files.

**Comment by herzadigital** [comment]
Hi,

Sorry for my late update. I noticed I made something wrong in my crontab so it doesn’t run properly. But I have fix it and its running at the moment. As for this “Mirror file should be placed in mirrors.d/ folder like other mirrors files.” Can you explain me more? I didn’t catch with you mean by this.

Looking forward to hear from you soon.


Sincerely,

Hernan Gibran Ramadhan
=====================
***@***.***D73188.A16DA630]
Herza Digital Indonesia
Web Hosting, Virtualization and Colocation

PT. Herza Digital Indonesia
EightyEight@Kasablanka, Tower A – 12th Floor
Jl. Kasablanka Raya Kav. 88, South Jakarta 12870 - Indonesia
Phone: (021) 50515111<tel:02150515111> / Fax: (021) 5010 6321
Hotline / SMS: 0899-121-1111<https://api.whatsapp.com/send?phone=628991211111> (Call / SMS / WhatsApp)

MAKASSAR BRANCH:
GRAHA PENA TOWER, 5th Floor
Jl. Urip Sumoharjo No. 20, Makassar, Sulawesi Selatan 90231, INDONESIA

Website: www.herza.id<http://www.herza.id/>     |    Email: ***@***.******@***.***>

**Comment by andrewlukoshko** [comment]
I mean mirror files located in **mirrors.d** subdir:
https://github.com/AlmaLinux/mirrors/tree/master/mirrors.d
Your pull request creates file in root of our repository here:
https://github.com/AlmaLinux/mirrors

Please update it to place your yml file in mirrors.d subdir.

**Comment by herzadigital** [comment]
Hi,

I have create new file in https://github.com/AlmaLinux/mirrors/tree/master/mirrors.d as per your request. Have you check it?


Sincerely,

Hernan Gibran Ramadhan
=====================
***@***.***D7339B.C109EE80]
Herza Digital Indonesia
Web Hosting, Virtualization and Colocation

PT. Herza Digital Indonesia
EightyEight@Kasablanka, Tower A – 12th Floor
Jl. Kasablanka Raya Kav. 88, South Jakarta 12870 - Indonesia
Phone: (021) 50515111<tel:02150515111> / Fax: (021) 5010 6321
Hotline / SMS: 0899-121-1111<https://api.whatsapp.com/send?phone=628991211111> (Call / SMS / WhatsApp)

MAKASSAR BRANCH:
GRAHA PENA TOWER, 5th Floor
Jl. Urip Sumoharjo No. 20, Makassar, Sulawesi Selatan 90231, INDONESIA

Website: www.herza.id<http://www.herza.id/>     |    Email: ***@***.******@***.***>

**Comment by andrewlukoshko** [comment]
Duplicates https://github.com/AlmaLinux/mirrors/pull/115
Closing.

**Pull request closed without merging**
