### PR TITLE
alma.acidman.thelefty.org is now open to the world

### PR DESCRIPTION
**Pull request by metalefty**
While here, fix sponsor_url.

### CODE REVIEW

**Comment by jonathanspw** [comment]
Do you still want the previously-defined subnets and ASN to hit your mirror primarily?  If so, those sections should stay.

**Comment by metalefty** [comment]
Yes, I'll put it back and add an IPv6 subnet.

**Comment by jonathanspw** [comment]
Oh I missed the fact that you did leave the ASN.  If the subnets are within the defined ASN then there's no need for the subnets.

Also, thanks for making it public :)

**Comment by metalefty** [comment]
Understood, thanks!

**Comment by metalefty** [comment]
@jonathanspw Just curious, when will it appear on mirrors.almalinux.org?

**Comment by codyro** [comment]
This should be appearing by now. 

I'll check once I'm on the PC, or @soksanichenko can shed some insight as well.

**Pull request merged**
