### PR TITLE
Create mirror.niif.hu.yml

### PR DESCRIPTION
**Pull request by northway**
New mirror - mirror.niif.hu

### CODE REVIEW

**Comment by northway** [comment]
Location: Budapest, Hungary

**Comment by andrewlukoshko** [comment]
Hello and thank you for mirror!
Please check your cron because looks like mirror is not updating.

**Comment by northway** [comment]
Thanks, I fixed the cronjob.

**Comment by andrewlukoshko** [comment]
Sorry but it's still not in sync. Was last updated yesterday.

**Comment by northway** [comment]
There was a typo in the script. I checked it multiple times, the sync is okay now.

**Comment by andrewlukoshko** [comment]
Looks great now, thanks.
Merging.

**Pull request merged**
