### PR TITLE
add new mirror: linux.domainesia.com and mirror.nevacloud.com

### PR DESCRIPTION
**Pull request by harsxv**
add new mirror: linux.domainesia.com

### CODE REVIEW

**Comment by harsxv** [comment]
I have requested correction to MaxMind IP database geolocation. Waiting for this to be updated.

**Comment by michaelact** [comment]
Hi, do you still keep AlmaLinux 8.3?

**Comment by harsxv** [comment]
> Hi, do you still keep AlmaLinux 8.3? Thank you.

Hi, we don't. If you need, you can find on the vaults.
http://repo.almalinux.org/vault/8.3/isos/x86_64/

Thank you.

**Comment by harsxv** [comment]
@michaelact I don't see any other Indonesia mirror provide this vaults.
If you want, I can sync up this. But due this will consume our international network, I need to do this at midnight.

**Comment by michaelact** [comment]
> @michaelact I don't see another Indonesia mirror provide this vaults. If you want, I can sync this up. But due this will consume our international network, I need to do this at midnight. We still have a sync progress with other mirrors. Please kindly wait.

No, its okay. I will give a try to 8.5 instead. Thank you for your help. 😃

**Comment by srbala** [comment]
@harsxv Please review/fix the GitHub CI failure https://github.com/AlmaLinux/mirrors/runs/5991008524?check_suite_focus=true

**Comment by harsxv** [comment]
```
2022-04-12 13:38:29,707 | __main__ | ERROR | Mirror "mirror.nevacloud.com" has invalid geodata. Please check your data on "https://nominatim.openstreetmap.org/ui/details.html"
2022-04-12 13:38:30,212 | __main__ | ERROR | Mirror "linux.domainesia.com" has invalid geodata. Please check your data on "https://nominatim.openstreetmap.org/ui/details.html"
```

I still waiting for updates geolocation from MaxMind.

**Comment by harsxv** [comment]
Hello @srbala ,

I've corrected geolocation in MaxMind, but they just update like this. Location: "Indonesia/Asia"
grafik

Should I edit my location details in the YAML files?

**Comment by harsxv** [comment]
Hello @jonathanspw 

My mirror is not listed in https://mirrors.almalinux.org/. Can you check it?
```
-   http: http://linux.domainesia.com/almalinux
-   https: https://linux.domainesia.com/almalinux
-   rsync: rsync://linux.domainesia.com/almalinux

-   http: http://mirror.nevacloud.com/almalinux
-   https: https://mirror.nevacloud.com/almalinux
-   rsync: rsync://mirror.nevacloud.com/almalinux
```

Thank you.

**Pull request merged**
