### PR TITLE
Added Geolocation for mirror

### PR DESCRIPTION
**Pull request by whoisrry**

### CODE REVIEW

**Comment by jonathanspw** [comment]
Please remove the committed file named `mirrors.d/update for mirror.dewabiz.com.yaml` and rebase your changes on `mirrors.d/mirror.dewabiz.com.yaml` using the master branch.

**Comment by whoisrry** [comment]
The file deleted and the changes are rebased
Thanks

**Comment by jonathanspw** [comment]
The PR is still conflicting.

**Comment by jonathanspw** [comment]
@whoisrry can you get this taken care of soon so we can get this merged?

**Pull request closed without merging**
