### PR TITLE
Add almalinux.ipacct.com

### PR DESCRIPTION
**Pull request by bbonev**
Note: the mirror is still in the initial rsync

### CODE REVIEW

**Comment by jonathanspw** [comment]
CI is likely to fail if the initial sync isn't done.  Are you pulling from the master rsync repo or one geographically-close to you?  If you already have the cron setup from the proper source then I can go ahead and merge this and the mirror will automatically get added into the mirrorlist when the sync is done.

**Comment by bbonev** [comment]
Pulling from the master repo. There are still things that need to be configured, I will post a comment here after done.

**Comment by jonathanspw** [comment]
> Pulling from the master repo. There are still things that need to be configured, I will post a comment here after done.

Just checking in.  The directory structure on your mirror looks a bit odd, like your sync is moving things around.

**Comment by bbonev** [comment]
Now it is synced, please check

**Comment by jonathanspw** [comment]
Thank you!

**Pull request merged**
