### PR TITLE
Add HTTP service to mirrors.atlas.net.co.yml 

### PR DESCRIPTION
**Pull request by marcomuskus**

### CODE REVIEW

**Comment by codyro** [comment]
Looks like this is redirecting to `https`:

```shell
bash-3.2$ http -I http://mirrors.atlas.net.co/almalinux/
HTTP/1.1 301 Moved Permanently
Connection: keep-alive
Content-Length: 169
Content-Type: text/html
Date: Wed, 07 Feb 2024 02:24:36 GMT
Location: https://mirrors.atlas.net.co/almalinux/
Server: nginx/1.24.0
```

**Comment by marcomuskus** [comment]
sorry, i fixed the web server configuration. can you please try again

**Comment by marcomuskus** [comment]
hi @codyro , any luck checking the HTTP port? thanks!

**Comment by codyro** [comment]
Thanks for fixing it up and contributing a mirror! 

You may be interested in becoming a member of the foundation now that you sponsor a mirror: https://almalinux.org/members/

**Pull request merged**
