### PR TITLE
updates DAL1 Hivelocity to list - Revised

### PR DESCRIPTION
**Pull request by HivelocityDonald**
PR 122 was closed because I incorrectly put it in the wrong place. This PR replaces PR 122 and is in correctly with mirrors.d.

### CODE REVIEW

**Comment by andrewlukoshko** [comment]
Hi @HivelocityDonald 
The mirror is not updating since June 2.
Please check your cron.
The same for almalinux-mirror.tpa.hivelocity.net

**Comment by HivelocityDonald** [comment]
Working on this today and will take a look for you @andrewlukoshko, Sorry about that!

**Comment by HivelocityDonald** [comment]
@andrewlukoshko @detriment has fixed this and he has issued PR #185 to fix the email as this is now going to be managed by the DevOps teams of Hivelocity.

**Comment by andrewlukoshko** [comment]
Thanks! Now mirrors look OK.

**Pull request merged**
