### PR TITLE
Add new mirror for Shiv Nadar Institution of Eminence

### PR DESCRIPTION
**Pull request by bhuvnesh-snioe**
Add new mirror for Shiv Nadar Institution of Eminence

### CODE REVIEW

**Comment by jonathanspw** [comment]
Thanks for the mirror!  I see that the DNS resolves to Cloudflare which isn't really ideal.  Can you point it directly at the mirror?

**Comment by bhuvnesh-snioe** [comment]
> Thanks for the mirror! I see that the DNS resolves to Cloudflare which isn't really ideal. Can you point it directly at the mirror?

Hi,

We have changed the necessary changes. Now it's resolving the mirror server IP.

**Comment by jonathanspw** [comment]
Looks great!  I notice that your organization seems to have its own ASN: AS132785

Would you like to configure our mirrorlist to send AlmaLinux mirrorlist requests from within your ASN to your mirror?

This is easily done by adding `asn: 132785` to the yaml config.

**Comment by bhuvnesh-snioe** [comment]
> Looks great! I notice that your organization seems to have its own ASN: AS132785
> 
> Would you like to configure our mirrorlist to send AlmaLinux mirrorlist requests from within your ASN to your mirror?
> 
> This is easily done by adding `asn: 132785` to the yaml config.

Hi,

We have updated the asn number

**Pull request merged**
