### PR TITLE
Create krg.hoster.kz.yml

### PR DESCRIPTION
**Pull request by y-sokoloff**

### CODE REVIEW

**Comment by codyro** [comment]
Hello,

It doesn't appear the rsync server is working. Would you mind investigating before we merge this in?

```
rsync --list-only rsync://krg.hoster.kz/almalinux/                                                                                               ✔  13:16:32
rsync: failed to connect to krg.hoster.kz: Connection refused (61)
rsync error: error in socket IO (code 10) at /AppleInternal/Library/BuildRoots/0032d1ee-80fd-11ee-8227-6aecfccc70fe/Library/Caches/com.apple.xbs/Sources/rsync/rsync/clientserver.c(109) [receiver=2.6.9]
```

```
nmap -p 873 krg.hoster.kz                                                                                                                        ✔  13:17:15
Starting Nmap 7.94 ( https://nmap.org ) at 2024-01-16 13:17 EST
Nmap scan report for krg.hoster.kz (188.241.217.254)
Host is up (0.20s latency).

PORT    STATE  SERVICE
873/tcp closed rsync
```

Thanks!

**Comment by y-sokoloff** [comment]
Thank you for the message! We found the problem and will contact you later. Сообщение, полученное 17 янв. 2024 г. в 0:18 от Cody Robertson ***@***.***>: Hello, It doesn't appear the rsync server is working. Would you mind investigating before we merge this in? rsync --list-only rsync://krg.hoster.kz/almalinux/  ✔  13:16:32 rsync: failed to connect to krg.hoster.kz: Connection refused (61) rsync error: error in socket IO (code 10) at /AppleInternal/Library/BuildRoots/0032d1ee-80fd-11ee-8227-6aecfccc70fe/Library/Caches/com.apple.xbs/Sources/rsync/rsync/clientserver.c(109) [receiver=2.6.9] nmap -p 873 krg.hoster.kz  ✔  13:17:15 Starting Nmap 7.94 ( https://nmap.org ) at 2024-01-16 13:17 EST Nmap scan report for krg.hoster.kz (188.241.217.254) Host is up (0.20s latency). PORT STATE SERVICE 873/tcp closed rsync Thanks! — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you authored the thread. Message ID: ***@***.***>

**Comment by codyro** [comment]
The mirror appears to be fully down at this time. I'll be closing this PR but please feel free to open a new one when everything is back online. Thanks for your contribution!

**Comment by y-sokoloff** [comment]
Hello, host is available now. Can you please check again and add us to public mirrors? Hello, It doesn't appear the rsync server is working. Would you mind investigating before we merge this in? rsync --list-only rsync://krg.hoster.kz/almalinux/  ✔  13:16:32 rsync: failed to connect to krg.hoster.kz: Connection refused (61) rsync error: error in socket IO (code 10) at /AppleInternal/Library/BuildRoots/0032d1ee-80fd-11ee-8227-6aecfccc70fe/Library/Caches/com.apple.xbs/Sources/rsync/rsync/clientserver.c(109) [receiver=2.6.9] nmap -p 873 krg.hoster.kz  ✔  13:17:15 Starting Nmap 7.94 ( https://nmap.org ) at 2024-01-16 13:17 EST Nmap scan report for krg.hoster.kz (188.241.217.254) Host is up (0.20s latency). PORT STATE SERVICE 873/tcp closed rsync Thanks! — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you authored the thread. Message ID: ***@***.***>

**Comment by codyro** [comment]
Hello,

It looks like the mirror isn't updating properly (the last update being on `29-Jan-2024 14:54`). The `rsync` server also appears to be down:

```
nmap -p 873 krg.hoster.kz                                        
Starting Nmap 7.94 ( https://nmap.org ) at 2024-01-31 17:41 EST
Nmap scan report for krg.hoster.kz (188.241.217.254)
Host is up (0.17s latency).

PORT    STATE  SERVICE
873/tcp closed rsync
```

Once these issues are resolved we can merge this in :).

**Comment by y-sokoloff** [comment]
[root@***** ~]# nmap -p 873 krg.hoster.kz Starting Nmap 6.40 ( http://nmap.org ) at 2024-02-02 09:30 +06 sendto in send_ip_packet_sd: sendto(4, packet, 40, 0, 188.241.217.254, 16) => Op eration not permitted Offending packet: TCP 194.146.42.42:42179 > 188.241.217.254:80 A ttl=44 id=51818 iplen=40 seq=0 win=1024 Nmap scan report for krg.hoster.kz (188.241.217.254) Host is up (0.013s latency). PORT STATE SERVICE 873/tcp closed rsync Nmap done: 1 IP address (1 host up) scanned in 0.76 seconds Host is UP Сообщение, полученное 1 февр. 2024 г. в 4:43 от Cody Robertson ***@***.***>: Hello, It looks like the mirror isn't updating properly (the last update being on 29-Jan-2024 14:54 ). The rsync server also appears to be down: nmap -p 873 krg.hoster.kz Starting Nmap 7.94 ( https://nmap.org ) at 2024-01-31 17:41 EST Nmap scan report for krg.hoster.kz (188.241.217.254) Host is up (0.17s latency). PORT STATE SERVICE 873/tcp closed rsync Once these issues are resolved we can merge this in :). — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you authored the thread. Message ID: ***@***.***>

**Pull request closed without merging**
