### PR TITLE
Create mirrors.neterra.net.yaml

### PR DESCRIPTION
**Pull request by ktsonevski**

### CODE REVIEW

**Comment by jonathanspw** [comment]
Thanks for the mirror!

**Comment by metalefty** [comment]
@jonathanspw Hi, the yaml file is created wrong place.

**Comment by ktsonevski** [comment]
Can we move it to the right place?

**Comment by jonathanspw** [comment]
Fixed via https://github.com/AlmaLinux/mirrors/commit/c5a17606fe082a2a9051c6fd7ad4d077f2eb5040

Good catch @metalefty

**Pull request merged**
