### PR TITLE
add mirror almalinux.pars.host

### PR DESCRIPTION
**Pull request by serverpars**
add pars.host almalinux mirror to the public repository

### CODE REVIEW

**Comment by jonathanspw** [comment]
The URL https://almalinux.pars.host currently 403s.  Can you fix this?

**Comment by serverpars** [comment]
Hello
It's already fixed

Thanks

**Comment by serverpars** [comment]
> The URL https://almalinux.pars.host currently 403s. Can you fix this?
@jonathanspw 
The issue has been resolved. could you please check it again ?

**Comment by codyro** [comment]
Thanks for the mirror! We were waiting for it to fully sync before merging it in :).

**Comment by serverpars** [comment]
@jonathanspw @codyro @ramereth @bluet 
Hello friends, even though we have done all the steps of setting up the mirror carefully, our mirror is still not listed. please guide me

**Pull request merged**
