### PR TITLE
Add mirror mirror.fysik.dtu.dk

### PR DESCRIPTION
**Pull request by OleHolmNielsen**
Thanks for providing AlmaLinux!  We'd like to become a mirror site.

### CODE REVIEW

**Comment by andrewlukoshko** [comment]
You're welcome! Waiting for sync.

**Comment by OleHolmNielsen** [comment]
The sync has been completed, and a cron job will sync every 3 hours now.

**Comment by OleHolmNielsen** [comment]
May I suggest adding the rsync options "--no-owner --no-group" to the recommended AlmaLinux rsync commands?
Our downloaded files have owner=10568 and group=10568, so I had to fix that.
Thanks, Ole

**Comment by andrewlukoshko** [comment]
Thanks for idea, we'll discuss.
Merged.

**Pull request merged**
