### PR TITLE
Add mirror.isoc.org.il

### PR DESCRIPTION
**Pull request by meir44**
Hi,
As requested by users, another almalinux mirror at 192.115.2.70 and 2a01:4280:2:20::2
Best regards

### CODE REVIEW

**Comment by jonathanspw** [comment]
There appears to be content missing from https://mirror.isoc.org.il/pub/almalinux that should be synced.  Can you verify that your rsync is complete and functioning correctly?

**Comment by meir44** [comment]
Sure. I'll check the sync

**Comment by codyro** [comment]
Hello,

Any update on this? It appears to still be missing some content.

**Comment by meir44** [comment]
It took forever to sync. Seems to be OK now

**Comment by meir44** [comment]
Hi,
Waiting for approval since 3 days already. @codyro 
Thanks

**Comment by codyro** [comment]
It doesn't appear this is syncing properly still--the last sync was on the 29th. Would you mind checking you cron? 

https://mirror.isoc.org.il/pub/almalinux/timestamp.txt

**Comment by meir44** [comment]
Sorry, my bad.
Synced

**Comment by meir44** [comment]
This bs is exhausting and taking far too long. If you know what is the geodata problem or can provide a log which says what is wrong i'll be happy to try my best to make it happen.
Otherwise Like I said, tried my best.  We'll close the request and move on with life.

**Comment by codyro** [comment]
Looks good now! Thanks for fixing this up and providing the mirror :)!

**Comment by meir44** [comment]
Thank you Cody, all the best.

**Pull request merged**
