### PR TITLE
almalinux.mirrors.behostings.net.yml

### PR DESCRIPTION
**Pull request by basilm1989**
---
name: almalinux.mirrors.behostings.net
address:
  http: http://almalinux.mirrors.behostings.net
  https: https://almalinux.mirrors.behostings.net
geolocation:
  country: BE
  state_province: Liege
  city: Aywaille
update_frequency: 3h
sponsor: Behostings
sponsor_url: https://www.behostings.com
email: basil.m@thgnet.net
...

### CODE REVIEW

**Comment by codyro** [comment]
Hello,

It appears your mirror is outdated (last update September 5th) causing it to fail the CI checks. Once you have this updated (please check for the cron & commands at https://wiki.almalinux.org/Mirrors.html) update this issue so we can re-run the checks and merge in your mirror.

**Comment by basilm1989** [comment]
> Hello,
> 
> It appears your mirror is outdated (last update September 5th) causing it to fail the CI checks. Once you have this updated (please check for the cron & commands at https://wiki.almalinux.org/Mirrors.html) update this issue so we can re-run the checks and merge in your mirror.

Okay, let me update it.

**Comment by basilm1989** [comment]
> @basilm1989 Hello. Looks like the SSL certificate is expired.

SSL has been renewed

**Comment by basilm1989** [comment]
> @basilm1989 Hello. Looks like the SSL certificate is expired.

Is this the command to sync the repo 

0 */3 * * * sleep $(((RANDOM\%3500)+1)) && /usr/bin/flock -n /var/run/almalinux_rsync.lock -c "/usr/bin/rsync -avSH -f 'R .~tmp~' --delete-delay --delay-updates rsync://rsync.repo.almalinux.org/almalinux/ /almalinux/dir/on/your/server/"

??  as some of the files

http://almalinux.mirrors.behostings.net/8.7/BaseOS/x86_64/os/repodata/repomd.xml   is missing

**Comment by basilm1989** [comment]
---
name: almalinux.mirrors.behostings.net
address:
  http: http://almalinux.mirrors.behostings.net
  https: https://almalinux.mirrors.behostings.net
geolocation:
  country: BE
  state_province: Liege
  city: Aywaille
update_frequency: 3h
sponsor: Behostings
sponsor_url: https://www.behostings.com
email: basil.m@thgnet.net
...

**Comment by basilm1989** [comment]
> > @basilm1989 Hello. Looks like the SSL certificate is expired.
> 
> SSL has been renewed

The CI checks
 failed 18 hours ago in 27.   When wil lthe next check run ?  or can we run it manually ?

**Comment by soksanichenko** [comment]
Hi.
I re-run the checks.

**Comment by basilm1989** [comment]
> Hi. I re-run the checks. Please check the results when them will be ready.

Could you re-run the checks

**Comment by codyro** [comment]
> Could you re-run the checks

The CI check has been re-ran. Please evaluate the results -- it appears you're missing several files in your mirror.

**Comment by basilm1989** [comment]
> > Could you re-run the checks
> 
> The CI check has been re-ran. Please evaluate the results -- it appears you're missing several files in your mirror.

The mentioned  file is there 

http://almalinux.mirrors.behostings.net/8.7/BaseOS/aarch64/os/repodata/repomd.xml

Please have a check why it fails, eventhough the file is present

**Comment by basilm1989** [comment]
> That file is absent for me. image

image

Works at my end

**Comment by basilm1989** [comment]
> Looks like you are using some caching proxy. Now I got code 200. Re-ran the checks.

Could you let me know why the repodata is gone to ".~tmp~"  >> like:

>>>  /home/mirror/8.7/AppStream/x86_64/os/repodata/.~tmp~

instead of >> /home/mirror/8.7/AppStream/x86_64/os/repodata

**Comment by basilm1989** [comment]
can you please initiate a check as its fully sync

**Comment by basilm1989** [comment]
> can you please initiate a check as its fully sync

can you please initiate a check as its fully sync

**Pull request merged**
