### PR TITLE
Create mirror.eyet.hosting.yml

### PR DESCRIPTION
**Pull request by MatijaTerzic**
Please add my mirror

### CODE REVIEW

**Comment by jonathanspw** [comment]
Your mirror is missing files.  Please verify your rsync is setup properly.

The version folders are there but not the files that reside directly in the root of the tree.

**Comment by MatijaTerzic** [comment]
Hello,

The rsync was not finished yet. I was a little to fast with my request. rsync is ready now. Also it supports IPv6

**Comment by MatijaTerzic** [comment]
> Hello,
> 
> The rsync was not finished yet. I was a little to fast with my request. rsync is ready now. Also it supports IPv6

Hello,

The rsync was not finished yet. I was a little to fast with my request. rsync is ready now. Also it supports IPv6

**Comment by MatijaTerzic** [comment]
> Your mirror is missing files. Please verify your rsync is setup properly.
> 
> The version folders are there but not the files that reside directly in the root of the tree.
Hello,

The rsync was not finished yet. I was a little to fast with my request. rsync is ready now. Also it supports IPv6

rsync is done

**Pull request merged**
