### PR TITLE
Add UCSB to mirror list.

### PR DESCRIPTION
**Pull request by vwbusguy**
Signed-off-by: Scott Williams <scottwilliams@ucsb.edu>

Unfortunately, current refresh rate is 24h.  I've sent a request to change that internally and will update it if that happens.

### CODE REVIEW

**Comment by jonathanspw** [comment]
Any luck getting the refresh rate changed?

**Comment by vwbusguy** [comment]
Sadly no.  24 hours is the default here and Sys Admins with a different department maintain it.  I've requested that they update this, but that hasn't happened and might not?  Maybe just add us to the list for serving isos for now if that's too long for packages?

**Comment by vwbusguy** [comment]
I sent a followup request about it today.

**Comment by jonathanspw** [comment]
Great.

We don't have anything in place currently to let us only accept the mirror for ISOs while not serving it for updates.  The system would detect the mirror as outdated and not serve it at all.

**Comment by vwbusguy** [comment]
I just heard back from the department and they advised that they've updated it to a 3 hour refresh rate, so I've updated the PR accordingly.

**Comment by jonathanspw** [comment]
The syncing is more frequent but I'm not sure it's every 3h.  Right now the last sync was about 4.5 hours ago.  I'm going to keep an eye on it.

Can you please also add the geolocation fields per the [sample](https://github.com/AlmaLinux/mirrors/blob/master/mirrors.d/repo.almalinux.org.yml).

Thanks :)

**Comment by vwbusguy** [comment]
I'll double check the sync time and add the geolocation stuff (I don't think that was in the sample when I originally submitted this PR).

**Review by jonathanspw — APPROVED** [review]

**Pull request merged**
