### PR TITLE
Update alma.intercloud.co.il.yml - Rsync

### PR DESCRIPTION
**Pull request by talintercloud**
Added Rsync

### CODE REVIEW

**Comment by jonathanspw** [comment]
There's a conflict with your PR.  Please rebase it to the latest version of the master repo.

Also add geolocation data.

**Comment by talintercloud** [comment]
I added Geolocation data.
Where exactly is this conflict? I see only one file by that name in each repo.

**Comment by talintercloud** [comment]
Hello,

I added geolocation data, and checked for duplicates and conflicts but
found nothing other than the same file, in my forked repo and in your repo,
where is the problem?

Tal Sabadia
*Support Team Leader*


T: 03-6283030
E: ***@***.***
W: www.intercloud.co.il

**Comment by talintercloud** [comment]
Nevermind, I think I got it, check again please.

Tal Sabadia
*Support Team Leader*


T: 03-6283030
E: ***@***.***
W: www.intercloud.co.il

**Comment by talintercloud** [comment]
Thanks, I still don't see the rsync in the mirrors page, is that going to
update or is there something wrong?

Tal Sabadia
*Support Team Leader*


T: 03-6283030
E: ***@***.***
W: www.intercloud.co.il

**Comment by jonathanspw** [comment]
It should show up within an hour of the merge.

**Pull request merged**
