### PR TITLE
Added FCIX/CodingFlyBoy MicroMirror

### PR DESCRIPTION
**Pull request by PhirePhly**
Thanks!

### CODE REVIEW

**Comment by PhirePhly** [comment]
I'm guessing the CI failure is due to 9 beta and not a problem on my end.

I guess I kind of jumped the gun on the maxmind update being approved. IPv6 update was submitted a few hours ago.

**Comment by bedanish11** [comment]
Hi mate, do you have any idea how to solve this 'version' issue in the config? Please let me know

**Comment by jonathanspw** [comment]
Your mirror is forcing the header/footer into xml files and breaking things.  ie:

```
2022-04-27T20:49:28+0000 INFO Downloading: https://mirrors.almalinux.org/mirrorlist/8/appstream
2022-04-27T20:49:28+0000 INFO Downloading: http://codingflyboy.mm.fcix.net/almalinux/8/AppStream/x86_64/os/repodata/repomd.xml
2022-04-27T20:49:28+0000 WARNING WARNING: Repomd xml parser: Unknown element "html"
```

I've removed it from our mirrorlist for now.  Please submit a new PR once this is fixed.

**Comment by jonathanspw** [comment]
Ref https://pagure.io/centos-infra/issue/758

**Pull request merged**
