### PR TITLE
Yet another IRAN mirror powered by Zagrio WebHosting

### PR DESCRIPTION
**Pull request by themshday**
All protocols with IPv4 & IPv6 supported mirror in IRAN.

### CODE REVIEW

**Comment by jonathanspw** [comment]
Your non-https URLs seem to be expecting SSL requests.  Can you check this?

**Comment by themshday** [comment]
> Your non-https URLs seem to be expecting SSL requests. Can you check this?

it has been fixed.

**Review by codyro — APPROVED** [review]

**Comment by codyro** [comment]
Thank you :)!

**Comment by codyro** [comment]
Would you mind merging master into this branch so we can merge it? Thanks!

**Comment by themshday** [comment]
done

**Pull request merged**
